"""Centralised application configuration loaded from environment variables.

Single-secret design: only GROQ_API_KEY is user-provided.
Internal credentials (Postgres, Neo4j) are auto-generated by bootstrap.
"""

from __future__ import annotations

import json
import os
import subprocess
from functools import lru_cache
from typing import Any

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _resolve_git_sha() -> str:
    """Resolve current git commit SHA from env var, CI metadata, or git command."""
    # 1. Explicit env var (injected by CI or Dockerfile)
    sha = os.environ.get("GIT_COMMIT_SHA", "")
    if sha:
        return sha[:12]
    # 2. Try git command
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            capture_output=True,
            text=True,
            timeout=3,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "dev"


GIT_COMMIT_SHA: str = _resolve_git_sha()


class Settings(BaseSettings):
    """Application settings — loaded from .env / environment variables.

    Single-secret architecture: only GROQ_API_KEY is required.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ── Application ──────────────────────────────────────────
    app_name: str = "MedicoBuddy"
    app_env: str = "production"
    app_debug: bool = False
    app_log_level: str = "INFO"
    app_secret_key: str = Field(default="", description="Auto-generated by bootstrap if absent")

    # ── FastAPI ──────────────────────────────────────────────
    api_host: str = "0.0.0.0"  # noqa: S104
    api_port: int = 8000
    # NOTE: Always 1 worker — in-memory embedding/index state is NOT worker-safe.
    api_workers: int = 1
    cors_origins: list[str] = ["http://localhost:8501", "http://localhost:7860"]

    # ── LLM Provider (Groq — THE ONLY EXTERNAL SECRET) ──────
    llm_provider: str = "groq"
    groq_api_key: str = ""
    groq_model_name: str = "llama-3.3-70b-versatile"
    # Also support GROQ_MODEL alias
    groq_model: str = ""
    llm_temperature: float = 0.1
    llm_max_tokens: int = 4096

    def get_groq_model(self) -> str:
        """Return the effective Groq model name."""
        return self.groq_model or self.groq_model_name or "llama-3.3-70b-versatile"

    # ── Embedding Model (Qwen3-Embedding-0.6B, local only) ───
    embedding_model: str = "Qwen/Qwen3-Embedding-0.6B"
    embedding_dimension: int = 1024
    embedding_timeout_seconds: int = 60

    # ── PostgreSQL / pgvector (mandatory vector database) ────
    enable_pgvector: bool = True
    postgres_dsn: str = ""  # Full DSN overrides individual fields
    postgres_host: str = "medicobuddy-postgres-pgvector"
    postgres_port: int = 5432
    postgres_db: str = "medicobuddy"
    postgres_user: str = "medicobuddy_internal"
    postgres_password: str = ""  # Auto-generated by bootstrap

    def get_postgres_dsn(self) -> str:
        """Return the effective PostgreSQL DSN."""
        if self.postgres_dsn:
            return self.postgres_dsn
        pw = self.postgres_password or "medicobuddy_dev"
        return (
            f"postgresql+asyncpg://{self.postgres_user}:{pw}"
            f"@{self.postgres_host}:{self.postgres_port}/{self.postgres_db}"
        )

    # ── Neo4j Knowledge Graph (Community Edition) ────────────
    neo4j_uri: str = "bolt://medicobuddy-neo4j-community:7687"
    neo4j_user: str = "neo4j"
    neo4j_password: str = ""  # Auto-generated by bootstrap
    neo4j_edition: str = "community"

    # ── MCP (optional future enhancement) ────────────────────
    mcp_enabled: bool = False  # MCP is optional; failure never blocks retrieval

    # ── Emergency Contacts ───────────────────────────────────
    emergency_contacts: dict[str, dict[str, str]] = Field(default_factory=lambda: {
        "IN": {"number": "112", "name": "Emergency Services India"},
        "US": {"number": "911", "name": "Emergency Services US"},
        "UK": {"number": "999", "name": "Emergency Services UK"},
        "EU": {"number": "112", "name": "Emergency Services EU"},
    })
    default_region: str = "IN"

    @field_validator("emergency_contacts", mode="before")
    @classmethod
    def parse_emergency_contacts(cls, v: Any) -> dict[str, dict[str, str]]:
        if isinstance(v, str):
            return json.loads(v)  # type: ignore[no-any-return]
        return v  # type: ignore[return-value]

    # ── Privacy & Regulatory ─────────────────────────────────
    enable_chat_history: bool = False
    data_retention_days: int = 30


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return a cached Settings instance."""
    return Settings()
